parameters:
    oro_workflow.action_factory.class: Oro\Component\ConfigExpression\Action\ActionFactory

    oro_workflow.action.tree.class: Oro\Component\ConfigExpression\Action\TreeExecutor
    oro_workflow.action.configurable.class: Oro\Component\ConfigExpression\Action\Configurable
    oro_workflow.action.assign_value.class: Oro\Component\ConfigExpression\Action\AssignValue
    oro_workflow.action.unset_value.class: Oro\Component\ConfigExpression\Action\UnsetValue
    oro_workflow.action.create_object.class: Oro\Component\ConfigExpression\Action\CreateObject
    oro_workflow.action.create_date.class: Oro\Component\ConfigExpression\Action\CreateDate
    oro_workflow.action.create_datetime.class: Oro\Component\ConfigExpression\Action\CreateDateTime
    oro_workflow.action.create_entity.class: Oro\Component\ConfigExpression\Action\CreateEntity
    oro_workflow.action.create_related_entity.class: Oro\Component\ConfigExpression\Action\CreateRelatedEntity
    oro_workflow.action.request_entity.class: Oro\Component\ConfigExpression\Action\RequestEntity
    oro_workflow.action.call_method.class: Oro\Component\ConfigExpression\Action\CallMethod
    oro_workflow.action.start_workflow.class: Oro\Bundle\WorkflowBundle\Model\Action\StartWorkflow
    oro_workflow.action.redirect.class: Oro\Component\ConfigExpression\Action\Redirect
    oro_workflow.action.format_string.class: Oro\Component\ConfigExpression\Action\FormatString
    oro_workflow.action.assign_active_user.class: Oro\Component\ConfigExpression\Action\AssignActiveUser
    oro_workflow.action.format_name.class: Oro\Component\ConfigExpression\Action\FormatName
    oro_workflow.action.traverse.class: Oro\Component\ConfigExpression\Action\Traverse
    oro_workflow.action.translate.class: Oro\Component\ConfigExpression\Action\TranslateAction
    oro_workflow.action.flash_message.class: Oro\Component\ConfigExpression\Action\FlashMessage
    oro_workflow.workflow.action.remove_entity.class:  Oro\Component\ConfigExpression\Action\RemoveEntity
    oro_workflow.workflow.action.assign_constant_value.class:  Oro\Component\ConfigExpression\Action\AssignConstantValue
    oro_workflow.workflow.action.copy_tagging.class:  Oro\Component\ConfigExpression\Action\CopyTagging
    oro_workflow.workflow.action.transit_workflow.class: Oro\Bundle\WorkflowBundle\Model\Action\TransitWorkflow
    oro_workflow.workflow.action.call_service_method.class: Oro\Component\ConfigExpression\Action\CallServiceMethod
    oro_workflow.workflow.action.run_action.class: Oro\Component\ConfigExpression\Action\RunAction
    oro_workflow.workflow.action.find_entities.class: Oro\Component\ConfigExpression\Action\FindEntities

services:
    oro_workflow.action_factory:
        class: %oro_workflow.action_factory.class%
        arguments:
            - @service_container
            - []

    oro_workflow.action.tree:
        class: %oro_workflow.action.tree.class%
        arguments:
            - @?logger
        tags:
            - { name: oro_workflow.action, alias: tree }

    oro_workflow.action.configurable:
        class: %oro_workflow.action.configurable.class%
        arguments:
            - @oro_workflow.action_assembler
        tags:
            - { name: oro_workflow.action, alias: configurable }

    oro_workflow.action.assign_value:
        class: %oro_workflow.action.assign_value.class%
        arguments:
            - @oro_action.context_accessor
        tags:
            - { name: oro_workflow.action, alias: assign_value }

    oro_workflow.action.unset_value:
        class: %oro_workflow.action.unset_value.class%
        arguments:
            - @oro_workflow.action.assign_value
        tags:
            - { name: oro_workflow.action, alias: unset_value }

    oro_workflow.action.create_object:
        class: %oro_workflow.action.create_object.class%
        arguments:
            - @oro_action.context_accessor
        tags:
            - { name: oro_workflow.action, alias: create_object }

    oro_workflow.action.create_date:
        class: %oro_workflow.action.create_date.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_locale.settings
        tags:
            - { name: oro_workflow.action, alias: create_date }

    oro_workflow.action.create_datetime:
        class: %oro_workflow.action.create_datetime.class%
        arguments:
            - @oro_action.context_accessor
        tags:
            - { name: oro_workflow.action, alias: create_datetime }

    oro_workflow.action.create_entity:
        class: %oro_workflow.action.create_entity.class%
        arguments:
            - @oro_action.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.action, alias: create_entity }

    oro_workflow.action.create_related_entity:
        class: %oro_workflow.action.create_related_entity.class%
        arguments:
            - @oro_action.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.action, alias: create_related_entity }

    oro_workflow.action.request_entity:
        class: %oro_workflow.action.request_entity.class%
        arguments:
            - @oro_action.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.action, alias: request_entity|find_entity }

    oro_workflow.action.call_method:
        class: %oro_workflow.action.call_method.class%
        arguments:
            - @oro_action.context_accessor
        tags:
            - { name: oro_workflow.action, alias: call_method }

    oro_workflow.action.start_workflow:
        class: %oro_workflow.action.start_workflow.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_workflow.manager
        tags:
            - { name: oro_workflow.action, alias: start_workflow }

    oro_workflow.action.redirect:
        class: %oro_workflow.action.redirect.class%
        arguments:
            - @oro_action.context_accessor
            - @router
            - 'result.redirectUrl'
        tags:
            - { name: oro_workflow.action, alias: redirect }

    oro_workflow.action.format_string:
        class: %oro_workflow.action.format_string.class%
        arguments:
            - @oro_action.context_accessor
        tags:
            - { name: oro_workflow.action, alias: format_string }

    oro_workflow.action.assign_active_user:
        class: %oro_workflow.action.assign_active_user.class%
        arguments:
            - @oro_action.context_accessor
            - @security.context
        tags:
            - { name: oro_workflow.action, alias: assign_active_user|get_active_user }

    oro_workflow.action.format_name:
        class: %oro_workflow.action.format_name.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_entity.entity_name_resolver
        tags:
            - { name: oro_workflow.action, alias: format_name }

    oro_workflow.action.traverse:
        class: %oro_workflow.action.traverse.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_workflow.action.configurable
        tags:
            - { name: oro_workflow.action, alias: traverse|foreach }

    oro_workflow.action.translate:
        class: %oro_workflow.action.translate.class%
        arguments:
            - @oro_action.context_accessor
            - @translator
        tags:
            - { name: oro_workflow.action, alias: translate|trans }

    oro_workflow.action.flash_message:
        class: %oro_workflow.action.flash_message.class%
        arguments:
            - @oro_action.context_accessor
            - @translator
        calls:
            - [setRequest, [@?request=]]
        tags:
            - { name: oro_workflow.action, alias: flash_message }

    oro_workflow.workflow.action.remove_entity:
        class: %oro_workflow.workflow.action.remove_entity.class%
        arguments:
            - @oro_action.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.action, alias: remove_entity }

    oro_workflow.workflow.action.assign_constant_value:
        class: %oro_workflow.workflow.action.assign_constant_value.class%
        arguments:
            - @oro_action.context_accessor
        tags:
            - { name: oro_workflow.action, alias: assign_constant_value }

    oro_workflow.workflow.action.copy_tagging.class:
        class: %oro_workflow.workflow.action.copy_tagging.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_tag.tag.manager
            - @oro_tag.helper.taggable_helper
        tags:
            - { name: oro_workflow.action, alias: copy_tagging }

    oro_workflow.workflow.action.transit_workflow:
        class: %oro_workflow.workflow.action.transit_workflow.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_workflow.manager
        tags:
            - { name: oro_workflow.action, alias: transit_workflow }

    oro_workflow.function.call_service_method:
        class: %oro_workflow.workflow.action.call_service_method.class%
        arguments:
            - @oro_action.context_accessor
            - @service_container
        tags:
            - { name: oro_workflow.action, alias: call_service_method }

    oro_workflow.function.run_action:
        class: %oro_workflow.workflow.action.run_action.class%
        arguments:
            - @oro_action.context_accessor
            - @oro_action.manager
            - @oro_action.helper.context
        tags:
            - { name: oro_action.function, alias: run_action }
            - { name: oro_workflow.action, alias: run_action }

    oro_workflow.function.find_entities:
        class: %oro_workflow.workflow.action.find_entities.class%
        arguments:
            - @oro_action.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.action, alias: find_entities }
