parameters:
    oro_workflow.attribute_assembler.class: Oro\Bundle\WorkflowBundle\Model\AttributeAssembler
    oro_workflow.step_assembler.class: Oro\Bundle\WorkflowBundle\Model\StepAssembler
    oro_workflow.transition_assembler.class: Oro\Bundle\WorkflowBundle\Model\TransitionAssembler
    oro_workflow.workflow_assembler.class: Oro\Bundle\WorkflowBundle\Model\WorkflowAssembler
    oro_workflow.form_options_assembler.class: Oro\Bundle\WorkflowBundle\Model\FormOptionsAssembler

services:
    oro_workflow.attribute_assembler:
        class: %oro_workflow.attribute_assembler.class%
        arguments:
            - '@oro_workflow.attribute_guesser'
            - '@translator'

    oro_workflow.step_assembler:
        class: %oro_workflow.step_assembler.class%

    oro_workflow.transition_assembler:
        class: %oro_workflow.transition_assembler.class%
        arguments:
            - '@oro_workflow.form_options_assembler'
            - '@oro_action.expression.factory'
            - '@oro_action.action_factory'

    oro_workflow.workflow_assembler:
        class: %oro_workflow.workflow_assembler.class%
        arguments:
            - '@service_container'
            - '@oro_workflow.attribute_assembler'
            - '@oro_workflow.step_assembler'
            - '@oro_workflow.transition_assembler'
            - '@oro_workflow.restriction_assembler'
            - '@translator'

    oro_workflow.form_options_assembler:
        class: %oro_workflow.form_options_assembler.class%
        arguments:
            - '@oro_action.action_factory'
        calls:
            - [addConfigurationPass,  ['@oro_action.configuration_pass.replace_property_path']]

    oro_workflow.assembler.transition_trigger.cron:
        class: Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\TransitionCronTriggerAssembler
        public: false
        arguments:
            - '@oro_workflow.transition_trigger.trigger_cron_verifier'

    oro_workflow.assembler.transition_trigger.event:
        class: Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\TransitionEventTriggerAssembler
        public: false
        arguments:
            - '@oro_workflow.transition_trigger.trigger_event_verifier'

    oro_workflow.transition_trigger_assembler:
        class: 'Oro\Bundle\WorkflowBundle\Model\WorkflowTransitionTriggersAssembler'
        calls:
            - [registerAssembler, ['@oro_workflow.assembler.transition_trigger.event']]
            - [registerAssembler, ['@oro_workflow.assembler.transition_trigger.cron']]

    oro_workflow.restriction_assembler:
        class: 'Oro\Bundle\WorkflowBundle\Model\RestrictionAssembler'
