parameters:
    oro_workflow.pass.parameter.class: Oro\Bundle\WorkflowBundle\Model\Pass\ParameterPass

    oro_workflow.condition_assembler.class: Oro\Bundle\WorkflowBundle\Model\Condition\ConditionAssembler
    oro_workflow.post_action_assembler.class: Oro\Bundle\WorkflowBundle\Model\PostAction\PostActionAssembler
    oro_workflow.step_assembler.class: Oro\Bundle\WorkflowBundle\Model\StepAssembler
    oro_workflow.transition_assembler.class: Oro\Bundle\WorkflowBundle\Model\TransitionAssembler
    oro_workflow.workflow_assembler.class: Oro\Bundle\WorkflowBundle\Model\WorkflowAssembler

services:
    oro_workflow.pass.parameter:
        class: %oro_workflow.pass.parameter.class%
        arguments:
            - "data"

    oro_workflow.condition_assembler:
        class: %oro_workflow.condition_assembler.class%
        arguments:
            - @oro_workflow.condition_factory
            - @oro_workflow.pass.parameter

    oro_workflow.post_action_assembler:
        class: %oro_workflow.post_action_assembler.class%
        arguments:
            - @oro_workflow.post_action_factory
            - @oro_workflow.pass.parameter

    oro_workflow.step_assembler:
        class: %oro_workflow.step_assembler.class%

    oro_workflow.transition_assembler:
        class: %oro_workflow.transition_assembler.class%
        arguments:
            - @oro_workflow.condition_factory
            - @oro_workflow.post_action_factory

    oro_workflow.workflow_assembler:
        class: %oro_workflow.workflow_assembler.class%
        arguments:
            - @oro_workflow.configuration_tree
            - @oro_workflow.step_assembler
            - @oro_workflow.transition_assembler

