services:
    oro_workflow.cache.provider.process_trigger:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_process_trigger' ] ]

    oro_workflow.cache.provider.transition_trigger_event:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_workflow_transition_trigger_event' ] ]

    oro_workflow.cache.process_trigger:
        parent: Oro\Bundle\WorkflowBundle\Cache\EventTriggerCache
        calls:
            - [ setProvider, [ '@oro_workflow.cache.provider.process_trigger' ] ]
            - [ setEventTriggerRepository, [ '@oro_workflow.repository.process_trigger' ] ]

    oro_workflow.cache.transition_trigger_event:
        parent: Oro\Bundle\WorkflowBundle\Cache\EventTriggerCache
        calls:
            - [ setProvider, [ '@oro_workflow.cache.provider.transition_trigger_event' ] ]
            - [ setEventTriggerRepository, [ '@oro_workflow.repository.transition_event_trigger' ] ]
