services:
    oro_workflow.async.transition_trigger_event_processor:
        class: 'Oro\Bundle\WorkflowBundle\Async\TransitionTriggerEventProcessor'
        arguments:
            - '@doctrine'
            - '@oro_workflow.helper.transition_trigger_event'
            - '@oro_workflow.manager'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor', topicName: 'oro_message_queue.transition_trigger_event_message' }
