services:
    oro_workflow.expression.extension:
#        public: false
        class: Oro\Component\ConfigExpression\Extension\DependencyInjection\DependencyInjectionExtension
        arguments:
            - @service_container
            - {}

    oro_workflow.expression.context_accessor:
#        public: false
        class: Oro\Component\ConfigExpression\ContextAccessor

    oro_workflow.expression.pass.property_path:
#        public: false
        class: Oro\Component\ConfigExpression\ConfigurationPass\ReplacePropertyPath
        calls:
            - [setPrefix, ["data"]]

    oro_workflow.expression.factory:
        class: Oro\Component\ConfigExpression\ExpressionFactory
        arguments:
            - @oro_workflow.expression.context_accessor
        calls:
            - [addExtension, [@oro_workflow.expression.extension]]

    oro_workflow.expression.assembler:
        class: Oro\Component\ConfigExpression\ExpressionAssembler
        arguments:
            - @oro_workflow.expression.factory
        calls:
            - [addConfigurationPass, [@oro_workflow.expression.pass.property_path]]

    oro_workflow.condition.configurable:
        class: Oro\Bundle\WorkflowBundle\ConfigExpression\Configurable
        arguments:
            - @oro_workflow.expression.assembler
        tags:
            - { name: oro_workflow.expression, alias: configurable }

    oro_workflow.expression.andx:
        class: Oro\Component\ConfigExpression\Condition\Andx
        tags:
            - { name: oro_workflow.expression, alias: and }

    oro_workflow.expression.orx:
        class: Oro\Component\ConfigExpression\Condition\Orx
        tags:
            - { name: oro_workflow.expression, alias: or }

    oro_workflow.expression.not:
        class: Oro\Component\ConfigExpression\Condition\Not
        tags:
            - { name: oro_workflow.expression, alias: not }

    oro_workflow.expression.true:
        class: Oro\Component\ConfigExpression\Condition\True
        tags:
            - { name: oro_workflow.expression, alias: "true" }

    oro_workflow.expression.false:
        class: Oro\Component\ConfigExpression\Condition\False
        tags:
            - { name: oro_workflow.expression, alias: "false" }

    oro_workflow.expression.equal_to:
        class: Oro\Component\ConfigExpression\Condition\EqualTo
        tags:
            - { name: oro_workflow.expression, alias: eq|equal }

    oro_workflow.expression.not_equal_to:
        class: Oro\Component\ConfigExpression\Condition\NotEqualTo
        tags:
            - { name: oro_workflow.expression, alias: neq|not_equal }

    oro_workflow.expression.blank:
        class: Oro\Component\ConfigExpression\Condition\Blank
        tags:
            - { name: oro_workflow.expression, alias: empty|blank }

    oro_workflow.expression.not_blank:
        class: Oro\Component\ConfigExpression\Condition\NotBlank
        tags:
            - { name: oro_workflow.expression, alias: not_empty|not_blank }

    oro_workflow.expression.has_value:
        class: Oro\Component\ConfigExpression\Condition\HasValue
        tags:
            - { name: oro_workflow.expression, alias: has_value }

    oro_workflow.expression.not_has_value:
        class: Oro\Component\ConfigExpression\Condition\NotHasValue
        tags:
            - { name: oro_workflow.expression, alias: not_has_value }

    oro_workflow.expression.greater_than:
        class: Oro\Component\ConfigExpression\Condition\GreaterThan
        tags:
            - { name: oro_workflow.expression, alias: gt|greater }

    oro_workflow.expression.greater_than_or_equal:
        class: Oro\Component\ConfigExpression\Condition\GreaterThanOrEqual
        tags:
            - { name: oro_workflow.expression, alias: gte|ge|greater_or_equal }

    oro_workflow.expression.less_than:
        class: Oro\Component\ConfigExpression\Condition\LessThan
        tags:
            - { name: oro_workflow.expression, alias: lt|less }

    oro_workflow.expression.less_than_or_equal:
        class: Oro\Component\ConfigExpression\Condition\LessThanOrEqual
        tags:
            - { name: oro_workflow.expression, alias: lte|le|less_or_equal }

    oro_workflow.expression.acl_granted:
        class: Oro\Bundle\SecurityBundle\ConfigExpression\AclGranted
        arguments:
            - @oro_security.security_facade
            - @doctrine
        tags:
            - { name: oro_workflow.expression, alias: acl_granted }
