parameters:
    oro_workflow.configuration.provider.workflow_config.class: Oro\Bundle\WorkflowBundle\Configuration\WorkflowConfigurationProvider
    oro_workflow.configuration.config.workflow_sole.class: Oro\Bundle\WorkflowBundle\Configuration\WorkflowConfiguration
    oro_workflow.configuration.config.workflow_list.class: Oro\Bundle\WorkflowBundle\Configuration\WorkflowListConfiguration
    oro_workflow.configuration.builder.workflow_definition.class: Oro\Bundle\WorkflowBundle\Configuration\WorkflowDefinitionConfigurationBuilder

services:
    oro_workflow.configuration.config.workflow_sole:
        class: %oro_workflow.configuration.config.workflow_sole.class%

    oro_workflow.configuration.config.workflow_list:
        class: %oro_workflow.configuration.config.workflow_list.class%
        arguments:
            - @oro_workflow.configuration.config.workflow_sole

    oro_workflow.configuration.provider.workflow_config:
        class: %oro_workflow.configuration.provider.workflow_config.class%
        arguments:
            - %kernel.bundles%
            - @oro_workflow.configuration.config.workflow_list

    oro_workflow.configuration.builder.workflow_definition:
        class: %oro_workflow.configuration.builder.workflow_definition.class%
