datagrid:
    workflow-definitions-grid:
        options:
            entityHint: workflows
            export: false
        source:
            type: orm
            acl_resource: oro_workflow_definition_view
            query:
                select:
                    - w.id
                    - w.label
                    - w.system
                    - w.createdAt
                from:
                    - { table: %oro_workflow.workflow_definition.entity.class%, alias: w }
        columns:
            label:
                label: oro.workflow.workflow_definition.label
            createdAt:
                label: oro.workflow.workflow_definition.createdAt
            system:
                label: oro.workflow.workflow_definition.system
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_workflow_definition_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_workflow_definition_update
                params:     [ id ]
#            delete_link:
#                type:       url
#                route:      oro_api_delete_workflowdefinition
#                params:     [ id ]
        sorters:
            columns:
                label:
                    data_name: w.label
                status:
                    data_name: w.status
                createdAt:
                    data_name: w.createdAt
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        actions:
            view:
                type:          navigate
                acl_resource:  oro_workflow_definition_view
                label:         oro.workflow.workflow_definition.datagrid.view
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_workflow_definition_update
                label:        oro.workflow.workflow_definition.datagrid.update
                icon:          edit
                link:          update_link
#            delete:
#                type:          delete
#                acl_resource:  oro_workflow_definition_delete
#                label:         oro.workflow.workflow_definition.datagrid.delete
#                icon:          trash
#                link:          delete_link
        filters:
            columns:
                 label:
                    type: string
                    data_name: w.label
