datagrid:
    workflow-definitions-grid:
        options:
            entityHint: workflows
            export: false
        source:
            type: orm
            acl_resource: oro_workflow_definition_view
            query:
                select:
                    - w.name as id
                    - w.name
                    - w.name as workflowDefinition
                    - w.relatedEntity as className
                    - w.label
                    - w.system
                    - w.createdAt
                from:
                    - { table: %oro_workflow.workflow_definition.entity.class%, alias: w }
        columns:
            label:
                label: oro.workflow.workflowdefinition.name.label
            relatedEntity:
                label: Related entity
                data_name: className
                frontend_type: select
                choices: @oro_workflow.datagrid.workflow_definition_entity_name_provider->getRelatedEntitiesChoice
            system:
                label: oro.workflow.workflowdefinition.system.label
                frontend_type: boolean
            createdAt:
                label: oro.workflow.workflowdefinition.created_at.label
                frontend_type: datetime
        properties:
            id: ~
            name: ~
            workflowDefinition: ~
            update_link:
                type:       url
                route:      oro_workflow_definition_update
                params:     [ name ]
            clone_link:
                type:       url
                route:      oro_workflow_definition_clone
                params:     [ name ]
            delete_link:
                type:       url
                route:      oro_api_workflow_definition_delete
                params:     [ workflowDefinition ]
        sorters:
            columns:
                label:
                    data_name: w.label
                system:
                    data_name: w.system
                createdAt:
                    data_name: w.createdAt
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        actions:
            update:
                type:          navigate
                acl_resource:  oro_workflow_definition_update
                label:         oro.workflow.workflowdefinition.datagrid.update
                icon:          edit
                rowAction:     true
                link:          update_link
            clone:
                type:          navigate
                acl_resource:  oro_workflow_definition_create
                label:         oro.workflow.workflowdefinition.datagrid.clone
                icon:          copy
                link:          clone_link
            delete:
                type:          delete
                acl_resource:  oro_workflow_definition_delete
                label:         oro.workflow.workflowdefinition.datagrid.delete
                icon:          trash
                link:          delete_link
        action_configuration: [@oro_workflow.datagrid.action_permission_provider, "getWorkflowDefinitionPermissions"]
        filters:
            columns:
                label:
                    type: string
                    data_name: w.label
                relatedEntity:
                    type: choice
                    data_name: w.className
                    options:
                        field_options:
                            multiple: true
                            choices: @oro_workflow.datagrid.workflow_definition_entity_name_provider->getRelatedEntitiesChoice
                system:
                    type: boolean
                    data_name: w.system
                createdAt:
                    type:      datetime
                    data_name: w.createdAt
