datagrid:
    workflow-definitions-grid:
        options:
            entityHint: workflows
            export: false
        source:
            type: orm
            acl_resource: oro_workflow_definition_view
            query:
                select:
                    - w.name
                    - w.name as workflowDefinition
                    - w.label
                    - w.system
                    - w.createdAt
                from:
                    - { table: %oro_workflow.workflow_definition.entity.class%, alias: w }
        columns:
            label:
                label: oro.workflow.workflowdefinition.name.label
            system:
                label: oro.workflow.workflowdefinition.system.label
                frontend_type: boolean
            createdAt:
                label: oro.workflow.workflowdefinition.created_at.label
                frontend_type: datetime
        properties:
            name: ~
            workflowDefinition: ~
            update_link:
                type:       url
                route:      oro_workflow_definition_update
                params:     [ name ]
            delete_link:
                type:       url
                route:      oro_api_workflow_definition_delete
                params:     [ workflowDefinition ]
        sorters:
            columns:
                label:
                    data_name: w.label
                system:
                    data_name: w.system
                createdAt:
                    data_name: w.createdAt
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        actions:
            update:
                type:          navigate
                acl_resource:  oro_workflow_definition_update
                label:         oro.workflow.workflow_definition.datagrid.update
                icon:          edit
                rowAction:     true
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_workflow_definition_delete
                label:         oro.workflow.workflow_definition.datagrid.delete
                icon:          trash
                link:          delete_link
        filters:
            columns:
                label:
                    type: string
                    data_name: w.label
                system:
                    type: boolean
                    data_name: w.system
                createdAt:
                    type:      datetime
                    data_name: w.createdAt
