parameters:
    oro_workflow.entity_binder.class: Oro\Bundle\WorkflowBundle\Model\EntityBinder
    oro_workflow.entity_binder.doctrine_subscriber.class: Oro\Bundle\WorkflowBundle\EventListener\WorkflowBindEntitySubscriber

services:
    oro_workflow.entity_binder:
        class: %oro_workflow.entity_binder.class%
        arguments:
            - @oro_workflow.registry
            - @doctrine

    oro_workflow.entity_binder.doctrine_subscriber:
        class: %oro_workflow.entity_binder.doctrine_subscriber.class%
        arguments:
            - @oro_workflow.entity_binder
        tags:
            - { name: doctrine.event_subscriber }
