oro_entity_config:
    workflow:
        entity:
            items:
                active_workflow:
                    options:
                        priority:           200
                        default_value:      null
                    form:
                        type:               oro_workflow_select
                        options:
                            label:          'Active workflow'
                            required:       false
                            empty_value:    'none'
                            block:          other
