oro_entity_config:
    workflow:
        entity:
            items:
                primary:
                    options:
                        priority:           200
                        default_value:      null
                    form:
                        type:               oro_workflow_selector
                        options:
                            label:          'Primary workflow'
                            required:       false
                            empty_value:    'none'
                            block:          other
