oro_entity_config:
    workflow:
        entity:
            items:
                active_workflow:
                    options:
                        priority:           200
                        default_value:      null
                    form:
                        type:               oro_workflow_select
                        options:
                            label:          oro.workflow.entity_config.active_workflow.label
                            required:       false
                            empty_value:    oro.workflow.entity_config.active_workflow.none
                            block:          other
                show_step_in_grid:
                    options:
                        priority:           250
                        default_value:      true
                    form:
                        type:               choice
                        options:
                            label:          oro.workflow.entity_config.is_show_step_in_grid.label
                            required:       false
                            choices:
                                false:      oro.workflow.entity_config.is_show_step_in_grid.choice.hide
                                true:       oro.workflow.entity_config.is_show_step_in_grid.choice.show
                            empty_value:    false
                            block:          other
