parameters:
    oro_workflow.datagrid.action_permission_provider.class: Oro\Bundle\WorkflowBundle\Datagrid\ActionPermissionProvider
    oro_workflow.datagrid.workflow_definition_entity_name_provider.class: Oro\Bundle\WorkflowBundle\Datagrid\WorkflowDefinitionGridEntityNameProvider
    oro_workflow.datagrid.listener.workflow_step_column.class: Oro\Bundle\WorkflowBundle\Datagrid\WorkflowStepColumnListener

services:
    oro_workflow.datagrid.action_permission_provider:
        class: %oro_workflow.datagrid.action_permission_provider.class%
        arguments:
            - @oro_entity_config.provider.workflow

    oro_workflow.datagrid.workflow_definition_entity_name_provider:
        class: %oro_workflow.datagrid.workflow_definition_entity_name_provider.class%
        arguments:
            - @oro_entity_config.provider.entity
            - @doctrine.orm.entity_manager
            - @translator

    oro_workflow.datagrid.listener.workflow_step_column.class:
        class: %oro_workflow.datagrid.listener.workflow_step_column.class%
        arguments:
            - @oro_entity.doctrine_helper
            - @oro_entity_config.provider.workflow
            - @oro_workflow.manager
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before, method: onBuildBefore }
        calls:
            - [addWorkflowStepColumn, ["workflowStep"]]
            - [addWorkflowStepColumn, ["workflowStepLabel"]]
            - [addWorkflowStepColumn, ["step"]]
            - [addWorkflowStepColumn, ["stepLabel"]]
