parameters:
    oro_workflow.listener.subscriber.workflow_data_serialize.class: Oro\Bundle\WorkflowBundle\EventListener\WorkflowDataSerializeSubscriber
    oro_workflow.listener.subscriber.workflow_step.class: Oro\Bundle\WorkflowBundle\EventListener\WorkflowStepSubscriber
    oro_workflow.listener.subscriber.workflow_item.class: Oro\Bundle\WorkflowBundle\EventListener\WorkflowItemSubscriber

services:
    oro_workflow.listener.subscriber.workflow_data_serialize:
        class: %oro_workflow.listener.subscriber.workflow_data_serialize.class%
        arguments:
            - @oro_workflow.serializer.data.serializer
            - @oro_entity.doctrine_helper
        tags:
            - { name: doctrine.event_subscriber }

    oro_workflow.listener.subscriber.workflow_item:
        class: %oro_workflow.listener.subscriber.workflow_item.class%
        arguments:
            - @oro_entity.doctrine_helper
            - @oro_workflow.entity_connector
            - @oro_workflow.manager
        tags:
            - { name: doctrine.event_subscriber }
