placeholders:
    view_navButtons_before:
        label: Workflow Buttons
        items:
            workflow_buttons:
                order: 100
items:
   workflow_buttons:
        template: OroWorkflowBundle:Widget:buttons.html.twig
