placeholders:
    view_navButtons_before:
        label: Workflow Buttons
        items:
            workflow_buttons:
                order: 100
    index_navButtons_before:
        label: Workflow Buttons
        items:
            workflow_buttons:
                order: 100
    page_title_before:
        label: Workflow Steps
        items:
            workflow_steps:
                order: 100
items:
    workflow_buttons:
        template: OroWorkflowBundle:Widget:buttons.html.twig
    workflow_steps:
        template: OroWorkflowBundle:Widget:steps.html.twig
