parameters:
    oro_workflow.post_action_factory.class: Oro\Bundle\WorkflowBundle\Model\PostAction\PostActionFactory

    oro_workflow.post_action.tree.class: Oro\Bundle\WorkflowBundle\Model\PostAction\TreeExecutor
    oro_workflow.post_action.configurable.class: Oro\Bundle\WorkflowBundle\Model\PostAction\Configurable
    oro_workflow.post_action.assign_value.class: Oro\Bundle\WorkflowBundle\Model\PostAction\AssignValue
    oro_workflow.post_action.unset_value.class: Oro\Bundle\WorkflowBundle\Model\PostAction\UnsetValue
    oro_workflow.post_action.create_entity.class: Oro\Bundle\WorkflowBundle\Model\PostAction\CreateEntity
    oro_workflow.post_action.request_entity.class: Oro\Bundle\WorkflowBundle\Model\PostAction\RequestEntity
    oro_workflow.post_action.call_method.class: Oro\Bundle\WorkflowBundle\Model\PostAction\CallMethod
    oro_workflow.post_action.start_workflow.class: Oro\Bundle\WorkflowBundle\Model\PostAction\StartWorkflow
    oro_workflow.post_action.redirect.class: Oro\Bundle\WorkflowBundle\Model\PostAction\Redirect
    oro_workflow.post_action.redirect_to_workflow.class: Oro\Bundle\WorkflowBundle\Model\PostAction\RedirectToWorkflow

services:
    oro_workflow.post_action_factory:
        class: %oro_workflow.post_action_factory.class%
        arguments:
            - @service_container
            - []

    oro_workflow.post_action.tree:
        class: %oro_workflow.post_action.tree.class%
        arguments:
            - @?logger
        tags:
            - { name: oro_workflow.post_action, alias: tree }

    oro_workflow.post_action.configurable:
        class: %oro_workflow.post_action.configurable.class%
        arguments:
            - @oro_workflow.post_action_assembler
        tags:
            - { name: oro_workflow.post_action, alias: configurable }

    oro_workflow.post_action.assign_value:
        class: %oro_workflow.post_action.assign_value.class%
        arguments:
            - @oro_workflow.context_accessor
        tags:
            - { name: oro_workflow.post_action, alias: assign_value }

    oro_workflow.post_action.unset_value:
        class: %oro_workflow.post_action.unset_value.class%
        arguments:
            - @oro_workflow.post_action.assign_value
        tags:
            - { name: oro_workflow.post_action, alias: unset_value }

    oro_workflow.post_action.create_entity:
        class: %oro_workflow.post_action.create_entity.class%
        arguments:
            - @oro_workflow.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.post_action, alias: create_entity }

    oro_workflow.post_action.request_entity:
        class: %oro_workflow.post_action.request_entity.class%
        arguments:
            - @oro_workflow.context_accessor
            - @doctrine
        tags:
            - { name: oro_workflow.post_action, alias: request_entity|find_entity }

    oro_workflow.post_action.call_method:
        class: %oro_workflow.post_action.call_method.class%
        arguments:
            - @oro_workflow.context_accessor
        tags:
            - { name: oro_workflow.post_action, alias: call_method }

    oro_workflow.post_action.start_workflow:
        class: %oro_workflow.post_action.start_workflow.class%
        arguments:
            - @oro_workflow.context_accessor
            - @oro_workflow.manager
        tags:
            - { name: oro_workflow.post_action, alias: start_workflow }

    oro_workflow.post_action.redirect:
        class: %oro_workflow.post_action.redirect.class%
        arguments:
            - @oro_workflow.context_accessor
            - @router
            - 'result.redirectUrl'
        tags:
            - { name: oro_workflow.post_action, alias: redirect }

    oro_workflow.post_action.redirect_to_workflow:
        class: %oro_workflow.post_action.redirect_to_workflow.class%
        arguments:
            - @oro_workflow.post_action.redirect
        tags:
            - { name: oro_workflow.post_action, alias: redirect_to_workflow }
