definitions:
    test_definition:
        label: 'Test Definition'
        enabled: true
        entity: Oro\Bundle\UserBundle\Entity\User
        order: 20
        actions_configuration:
            - @assign_value: [$namePrefix, 'Pr.']

    another_definition:
        label: 'Another definition'
        entity: My\Entity
        actions_configuration: []

triggers:
    test_definition:
        -
            event: update
            field: loginCount
            queued: true
            time_shift: 123456
        -
            event: create
            queued: true
            time_shift: P6YT5M
        -
            event: delete
