config:
    paths:
        'oro/workflow-transition-handler': 'bundles/oroworkflow/js/transition-handler.js'
        'oro/workflow-save-and-transit-handler': 'bundles/oroworkflow/js/save-and-transit-handler.js'
        'oro/workflow-transition-executor': 'bundles/oroworkflow/js/transition-executor.js'