config:
    paths:
        'oroworkflow/js/transition-handler':                        'bundles/oroworkflow/js/transition-handler.js'
        'oroworkflow/js/save-and-transit-handler':                  'bundles/oroworkflow/js/save-and-transit-handler.js'
        'oroworkflow/js/transition-executor':                       'bundles/oroworkflow/js/transition-executor.js'

        'oro/workflow-management':                                  'bundles/oroworkflow/js/workflow-management/workflow-management.js'
        'oro/workflow-management/helper':                           'bundles/oroworkflow/js/workflow-management/helper'
        'oro/workflow-management/workflow/model':                   'bundles/oroworkflow/js/workflow-management/workflow/model.js'

        'oro/workflow-management/attribute/model':                  'bundles/oroworkflow/js/workflow-management/attribute/model.js'
        'oro/workflow-management/attribute/collection':             'bundles/oroworkflow/js/workflow-management/attribute/collection.js'
        'oro/workflow-management/attribute/form-option-view/list':  'bundles/oroworkflow/js/workflow-management/attribute/form-option-view/list.js'
        'oro/workflow-management/attribute/form-option-view/row':   'bundles/oroworkflow/js/workflow-management/attribute/form-option-view/row.js'
        'oro/workflow-management/attribute/form-option-view/edit':  'bundles/oroworkflow/js/workflow-management/attribute/form-option-view/edit.js'

        'oro/workflow-management/step/model':                       'bundles/oroworkflow/js/workflow-management/step/model.js'
        'oro/workflow-management/step/collection':                  'bundles/oroworkflow/js/workflow-management/step/collection.js'
        'oro/workflow-management/step/view/list':                   'bundles/oroworkflow/js/workflow-management/step/view/list.js'
        'oro/workflow-management/step/view/row':                    'bundles/oroworkflow/js/workflow-management/step/view/row.js'
        'oro/workflow-management/step/view/edit':                   'bundles/oroworkflow/js/workflow-management/step/view/edit.js'

        'oro/workflow-management/transition/model':                 'bundles/oroworkflow/js/workflow-management/transition/model.js'
        'oro/workflow-management/transition/collection':            'bundles/oroworkflow/js/workflow-management/transition/collection.js'
        'oro/workflow-management/transition/view/list':             'bundles/oroworkflow/js/workflow-management/transition/view/list.js'
        'oro/workflow-management/transition/view/row':              'bundles/oroworkflow/js/workflow-management/transition/view/row.js'
        'oro/workflow-management/transition/view/list-short':       'bundles/oroworkflow/js/workflow-management/transition/view/list-short.js'
        'oro/workflow-management/transition/view/row-short':        'bundles/oroworkflow/js/workflow-management/transition/view/row-short.js'
        'oro/workflow-management/transition/view/edit':             'bundles/oroworkflow/js/workflow-management/transition/view/edit.js'