parameters:
    oro_workflow.registry.class: Oro\Bundle\WorkflowBundle\Model\WorkflowRegistry

    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor

    oro_workflow.workflow_prototype.class: Oro\Bundle\WorkflowBundle\Model\Workflow
    oro_workflow.manager.class: Oro\Bundle\WorkflowBundle\Model\WorkflowManager

services:
    oro_workflow.context_accessor:
        class: %oro_workflow.context_accessor.class%

    oro_workflow.registry:
        class: %oro_workflow.registry.class%
        arguments:
            - @doctrine
            - @oro_workflow.workflow_assembler

    oro_workflow.workflow_prototype:
        class: %oro_workflow.workflow_prototype.class%
        scope: prototype

    oro_workflow.manager:
        class: %oro_workflow.manager.class%
        arguments:
            - @doctrine
            - @oro_workflow.registry
