parameters:
    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor
    oro_workflow.doctrine_helper.class: Oro\Bundle\WorkflowBundle\Model\DoctrineHelper
    oro_workflow.registry.class: Oro\Bundle\WorkflowBundle\Model\WorkflowRegistry
    oro_workflow.manager.class: Oro\Bundle\WorkflowBundle\Model\WorkflowManager
    oro_workflow.workflow_result.class: Oro\Bundle\WorkflowBundle\Model\WorkflowResult
    oro_workflow.process.process_factory.class: Oro\Bundle\WorkflowBundle\Model\ProcessFactory
    oro_workflow.process.process_handler.class: Oro\Bundle\WorkflowBundle\Model\ProcessHandler

services:
    oro_workflow.context_accessor:
        class: %oro_workflow.context_accessor.class%

    oro_workflow.doctrine_helper:
        class: %oro_workflow.doctrine_helper.class%
        arguments:
            - @doctrine

    oro_workflow.registry:
        class: %oro_workflow.registry.class%
        arguments:
            - @doctrine
            - @oro_workflow.workflow_assembler

    oro_workflow.manager:
        class: %oro_workflow.manager.class%
        arguments:
            - @doctrine
            - @oro_workflow.registry
            - @oro_workflow.doctrine_helper

    oro_workflow.process.process_factory:
        class: %oro_workflow.process.process_factory.class%
        arguments:
            - @oro_workflow.process.action_assembler

    oro_workflow.process.process_handler:
        class: %oro_workflow.process.process_handler.class%
        arguments:
            - @oro_workflow.process.process_factory
