parameters:
    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor
    oro_workflow.entity_connector.class: Oro\Bundle\WorkflowBundle\Model\EntityConnector
    oro_workflow.registry.class: Oro\Bundle\WorkflowBundle\Model\WorkflowRegistry
    oro_workflow.manager.class: Oro\Bundle\WorkflowBundle\Model\WorkflowManager
    oro_workflow.workflow_result.class: Oro\Bundle\WorkflowBundle\Model\WorkflowResult
    oro_workflow.workflow_definition.entity.class: Oro\Bundle\WorkflowBundle\Entity\WorkflowDefinition

services:
    oro_workflow.context_accessor:
        class: %oro_workflow.context_accessor.class%

    oro_workflow.entity_connector:
        class: %oro_workflow.entity_connector.class%

    oro_workflow.registry:
        class: %oro_workflow.registry.class%
        arguments:
            - @doctrine
            - @oro_workflow.workflow_assembler
            - @oro_entity_config.provider.workflow

    oro_workflow.manager:
        class: %oro_workflow.manager.class%
        arguments:
            - @doctrine
            - @oro_workflow.registry
            - @oro_entity.doctrine_helper
