parameters:
    oro_workflow.configuration_provider.class: Oro\Bundle\WorkflowBundle\Configuration\ConfigurationProvider
    oro_workflow.workflow_item_data_normalizer.class: Oro\Bundle\WorkflowBundle\Serializer\Normalizer\WorkflowDataNormalizer
    oro_workflow.workflow_item_serialize_subscriber.class: Oro\Bundle\WorkflowBundle\EventListener\WorkflowItemSerializeSubscriber

    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor

services:
    oro_workflow.configuration_provider:
        class: %oro_workflow.configuration_provider.class%
        arguments:
            - %kernel.bundles%

    oro_workflow.workflow_item_data_serializer:
        class: %serializer.class%
        arguments:
          - [@oro_workflow.workflow_item_data_normalizer]
          - [@serializer.encoder.json]

    oro_workflow.workflow_item_data_normalizer:
        class: %oro_workflow.workflow_item_data_normalizer.class%
        arguments: [@doctrine]

    oro_workflow.workflow_item_serialize_subscriber:
        class: %oro_workflow.workflow_item_serialize_subscriber.class%
        arguments:
            - @oro_workflow.workflow_item_data_serializer
        tags:
            - { name: doctrine.event_subscriber }

    oro_workflow.context_accessor:
        class: %oro_workflow.context_accessor.class%
