parameters:
    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor
    oro_workflow.metadata_manager.class: Oro\Bundle\WorkflowBundle\Model\MetadataManager
    oro_workflow.registry.class: Oro\Bundle\WorkflowBundle\Model\WorkflowRegistry
    oro_workflow.manager.class: Oro\Bundle\WorkflowBundle\Model\WorkflowManager

services:
    oro_workflow.context_accessor:
        class: %oro_workflow.context_accessor.class%

    oro_workflow.metadata_manager:
        class: %oro_workflow.metadata_manager.class%
        arguments:
            - @doctrine

    oro_workflow.registry:
        class: %oro_workflow.registry.class%
        arguments:
            - @doctrine
            - @oro_workflow.workflow_assembler

    oro_workflow.manager:
        class: %oro_workflow.manager.class%
        arguments:
            - @doctrine
            - @oro_workflow.registry
            - @oro_workflow.metadata_manager
