parameters:
    oro_workflow.configuration_provider.class: Oro\Bundle\WorkflowBundle\Configuration\ConfigurationProvider
    oro_workflow.configuration_tree.class: Oro\Bundle\WorkflowBundle\Configuration\ConfigurationTree
    oro_workflow.configuration_workflow_definition_builder.class: Oro\Bundle\WorkflowBundle\Configuration\ConfigurationWorkflowDefinitionBuilder

    oro_workflow.registry.class: Oro\Bundle\WorkflowBundle\Model\WorkflowRegistry

    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor
    oro_workflow.entity_binder.class: Oro\Bundle\WorkflowBundle\Model\EntityBinder

    oro_workflow.workflow_prototype.class: Oro\Bundle\WorkflowBundle\Model\Workflow
    oro_workflow.manager.class: Oro\Bundle\WorkflowBundle\Model\WorkflowManager

services:
    oro_workflow.configuration_tree:
        class: %oro_workflow.configuration_tree.class%

    oro_workflow.configuration_provider:
        class: %oro_workflow.configuration_provider.class%
        arguments:
            - %kernel.bundles%
            - @oro_workflow.configuration_tree

    oro_workflow.configuration_workflow_definition_builder:
        class: %oro_workflow.configuration_workflow_definition_builder.class%

    oro_workflow.context_accessor:
        class: %oro_workflow.context_accessor.class%

    oro_workflow.entity_binder:
        class: %oro_workflow.entity_binder.class%
        arguments:
            - @doctrine

    oro_workflow.registry:
        class: %oro_workflow.registry.class%
        arguments:
            - @doctrine
            - @oro_workflow.workflow_assembler

    oro_workflow.workflow_prototype:
        class: %oro_workflow.workflow_prototype.class%
        scope: prototype

    oro_workflow.manager:
        class: %oro_workflow.manager.class%
        arguments:
            - @doctrine
            - @oro_workflow.registry
            - @oro_workflow.entity_binder
