parameters:
    oro_workflow.attribute_guesser.class: Oro\Bundle\ActionBundle\Model\AttributeGuesser
    oro_workflow.context_accessor.class: Oro\Bundle\WorkflowBundle\Model\ContextAccessor
    oro_workflow.manager.class: Oro\Bundle\WorkflowBundle\Model\WorkflowManager
    oro_workflow.process_definition.entity.class: Oro\Bundle\WorkflowBundle\Entity\ProcessDefinition
    oro_workflow.process_trigger.entity.class: Oro\Bundle\WorkflowBundle\Entity\ProcessTrigger
    oro_workflow.process.process_factory.class: Oro\Bundle\WorkflowBundle\Model\ProcessFactory
    oro_workflow.process.process_handler.class: Oro\Bundle\WorkflowBundle\Model\ProcessHandler
    oro_workflow.process.schedule_policy.exclude_definitions.class: Oro\Bundle\WorkflowBundle\Model\ExcludeDefinitionsProcessSchedulePolicy
    oro_workflow.process.logger.class: Oro\Bundle\WorkflowBundle\Model\ProcessLogger
    oro_workflow.registry.class: Oro\Bundle\WorkflowBundle\Model\WorkflowRegistry
    oro_workflow.workflow_definition.entity.class: Oro\Bundle\WorkflowBundle\Entity\WorkflowDefinition
    oro_workflow.workflow_item.entity.class: Oro\Bundle\WorkflowBundle\Entity\WorkflowItem
    oro_workflow.workflow_result.class: Oro\Bundle\WorkflowBundle\Model\WorkflowResult
    oro_workflow.handler.transition_helper.class: Oro\Bundle\WorkflowBundle\Handler\Helper\TransitionHelper
    oro_workflow.handler.transition_handler.class: Oro\Bundle\WorkflowBundle\Handler\TransitionHandler
    oro_workflow.handler.start_transition_handler.class: Oro\Bundle\WorkflowBundle\Handler\StartTransitionHandler

    oro_workflow.entity.transition_trigger_cron.class: Oro\Bundle\WorkflowBundle\Entity\TransitionCronTrigger
    oro_workflow.entity.transition_trigger_event.class: Oro\Bundle\WorkflowBundle\Entity\TransitionEventTrigger

services:
    oro_workflow.attribute_guesser:
        class: '%oro_workflow.attribute_guesser.class%'
        arguments:
            - '@form.registry'
            - '@doctrine'
            - '@oro_entity_config.provider.entity'
            - '@oro_entity_config.provider.form'
        calls:
            # mapping from doctrine type to attribute parameters
            - [addDoctrineTypeMapping, ["string", "string"]]
            - [addDoctrineTypeMapping, ["integer", "integer"]]
            - [addDoctrineTypeMapping, ["smallint", "integer"]]
            - [addDoctrineTypeMapping, ["bigint", "integer"]]
            - [addDoctrineTypeMapping, ["boolean", "boolean"]]
            - [addDoctrineTypeMapping, ["decimal", "float"]]
            - [addDoctrineTypeMapping, ["date", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["time", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["datetime", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["datetimetz", "object", { class: "DateTime" }]]
            - [addDoctrineTypeMapping, ["text", "string"]]
            - [addDoctrineTypeMapping, ["array", "array"]]
            - [addDoctrineTypeMapping, ["simple_array", "array"]]
            - [addDoctrineTypeMapping, ["json_array", "array"]]
            - [addDoctrineTypeMapping, ["float", "float"]]
            - [addDoctrineTypeMapping, ["guid", "string"]]
            # custom types
            - [addDoctrineTypeMapping, ["percent", "float"]]
            - [addDoctrineTypeMapping, ["money", "float"]]
            # mapping from attribute type to form parameters
            - [addFormTypeMapping, ["string", "text"]]
            - [addFormTypeMapping, ["int", "integer", { precision: 0 }]]
            - [addFormTypeMapping, ["integer", "integer", { precision: 0 }]]
            - [addFormTypeMapping, ["bool", "checkbox"]]
            - [addFormTypeMapping, ["boolean", "checkbox"]]
            - [addFormTypeMapping, ["float", "number"]]
        deprecated: The "%service_id%" service is deprecated since since 1.10. Use "oro_action.attribute_guesser" instead

    oro_workflow.context_accessor:
        class: '%oro_workflow.context_accessor.class%'
        deprecated: The "%service_id%" service is deprecated since since 1.10. Use "oro_action.context_accessor" instead

    oro_workflow.datagrid.action.workflow_activate:
        class: 'Oro\Bundle\WorkflowBundle\Datagrid\Action\WorkflowActivateAction'
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.action.type, type: workflow-activate }

    oro_workflow.datagrid.action.workflow_deactivate:
        class: 'Oro\Bundle\WorkflowBundle\Datagrid\Action\WorkflowDeactivateAction'
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.action.type, type: workflow-deactivate }

    oro_workflow.entity_connector:
        class: 'Oro\Bundle\WorkflowBundle\Model\WorkflowEntityConnector'
        arguments:
            - '@doctrine'

    oro_workflow.manager:
        class: 'Oro\Bundle\WorkflowBundle\Model\WorkflowManager'
        arguments:
            - '@oro_workflow.registry'
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.changes.event.dispatcher'
            - '@oro_workflow.entity_connector'
        calls:
            - [addApplicabilityFilter, ['@oro_workflow.applicability_filter.exclusive_record_group']]

    oro_workflow.applicability_filter.exclusive_record_group:
        class: 'Oro\Bundle\WorkflowBundle\Model\WorkflowExclusiveRecordGroupFilter'
        arguments:
            - '@oro_entity.doctrine_helper'

    oro_workflow.abstract.workflow_aware_manager:
        class: 'Oro\Bundle\WorkflowBundle\Model\WorkflowAwareManager'
        abstract: true
        arguments:
            - '@oro_workflow.manager'

    oro_workflow.process.process_factory:
        class: '%oro_workflow.process.process_factory.class%'
        arguments:
            - '@oro_workflow.action_assembler'
            - '@oro_workflow.expression.factory'

    oro_workflow.process.process_handler:
        class: '%oro_workflow.process.process_handler.class%'
        arguments:
            - '@oro_workflow.process.process_factory'
            - '@oro_workflow.process.logger'
            - '@event_dispatcher'

    oro_workflow.process.schedule_policy.exclude_definitions:
        class: '%oro_workflow.process.schedule_policy.exclude_definitions.class%'
        tags:
            - { name: kernel.event_listener, event: oro_workflow.process.handle_before, method: onProcessHandleBefore }
            - { name: kernel.event_listener, event: oro_workflow.process.handle_after_flush, method: onProcessHandleAfterFlush }

    oro_workflow.process.schedule_policy:
        alias: oro_workflow.process.schedule_policy.exclude_definitions

    oro_workflow.process.logger:
        class: '%oro_workflow.process.logger.class%'
        arguments:
            - '@oro_entity.doctrine_helper'
            - "@?logger"

    oro_workflow.registry:
        class: '%oro_workflow.registry.class%'
        arguments:
            - '@doctrine'
            - '@oro_workflow.workflow_assembler'
            - '@oro_featuretoggle.checker.feature_checker'

    oro_workflow.permission_registry:
        class: 'Oro\Bundle\WorkflowBundle\Model\WorkflowPermissionRegistry'
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.registry'

    oro_workflow.exclusion_provider.workflow_item_step:
        class: 'Oro\Bundle\WorkflowBundle\Provider\WorkflowExclusionProvider'
        public: false
        tags:
            - { name: oro_entity.exclusion_provider.api }

    oro_workflow.provider.virtual_relation.workflow:
        class: 'Oro\Bundle\WorkflowBundle\Provider\WorkflowVirtualRelationProvider'
        arguments:
            - '@oro_workflow.registry'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: oro_entity.virtual_relation_provider, priority: 150 }

    oro_workflow.handler.transition_helper:
        class: '%oro_workflow.handler.transition_helper.class%'
        arguments:
            - '@fos_rest.view_handler'
            - '@twig'

    oro_workflow.handler.transition_handler:
        class: '%oro_workflow.handler.transition_handler.class%'
        arguments:
            - '@oro_workflow.manager'
            - '@oro_workflow.handler.transition_helper'
            - '@logger'

    oro_workflow.handler.start_transition_handler:
        class: '%oro_workflow.handler.start_transition_handler.class%'
        arguments:
            - '@oro_workflow.manager'
            - '@oro_workflow.serializer.data.serializer'
            - '@oro_workflow.handler.transition_helper'

    oro_workflow.validation_loader:
        class: 'Oro\Bundle\WorkflowBundle\Validator\WorkflowValidationLoader'
        public: false
        arguments:
            - '@oro_workflow.permission_registry'
            - '@oro_workflow.restriction.manager'
            - '@oro_entity_config.link.entity_manager'

    oro_workflow.restriction.manager:
        class: 'Oro\Bundle\WorkflowBundle\Restriction\RestrictionManager'
        public: false
        arguments:
            - '@oro_workflow.registry'
            - '@oro_entity.doctrine_helper'

    oro_workflow.changes.event.dispatcher:
        class: 'Symfony\Component\EventDispatcher\EventDispatcher'

    oro_workflow.handler.workflow_definition:
        class: 'Oro\Bundle\WorkflowBundle\Handler\WorkflowDefinitionHandler'
        arguments:
            - '@oro_workflow.changes.event.dispatcher'
            - '@doctrine'

    oro_workflow.process.cron_scheduler:
        class: 'Oro\Bundle\WorkflowBundle\Cron\ProcessTriggerCronScheduler'
        arguments:
            - '@oro_cron.deferred_scheduler'

    oro_workflow.process.definitions_configurator:
        class: 'Oro\Bundle\WorkflowBundle\Configuration\ProcessDefinitionsConfigurator'
        arguments:
            - '@oro_workflow.configuration.builder.process_configuration'
            - '@doctrine'
            - '%oro_workflow.process_definition.entity.class%'

    oro_workflow.process.triggers_configurator:
        class: 'Oro\Bundle\WorkflowBundle\Configuration\ProcessTriggersConfigurator'
        arguments:
            - '@oro_workflow.configuration.builder.process_configuration'
            - '@oro_workflow.process.cron_scheduler'
            - '@doctrine'
            - '%oro_workflow.process_trigger.entity.class%'

    oro_workflow.process.configurator:
        class: 'Oro\Bundle\WorkflowBundle\Configuration\ProcessConfigurator'
        public: true
        arguments:
            - '@doctrine'
            - '@oro_workflow.process.definitions_configurator'
            - '@oro_workflow.process.triggers_configurator'
            - '%oro_workflow.process_definition.entity.class%'

    oro_workflow.repository.workflow_item:
        class: 'Oro\Bundle\WorkflowBundle\Entity\Repository\WorkflowItemRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - '%oro_workflow.workflow_item.entity.class%'

    oro_workflow.repository.process_trigger:
        class: 'Oro\Bundle\WorkflowBundle\Entity\Repository\ProcessTriggerRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - '%oro_workflow.process_trigger.entity.class%'

    oro_workflow.repository.transition_event_trigger:
        class: 'Oro\Bundle\WorkflowBundle\Entity\Repository\TransitionEventTriggerRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - '%oro_workflow.entity.transition_trigger_event.class%'

    oro_workflow.helper.workflow_aware_entity_fetcher:
        class: 'Oro\Bundle\WorkflowBundle\Helper\WorkflowAwareEntityFetcher'
        public: true
        arguments:
            - '@doctrine'

    oro_workflow.helper.transition_event_trigger:
        class: 'Oro\Bundle\WorkflowBundle\Helper\TransitionEventTriggerHelper'
        public: false
        arguments:
            - '@oro_workflow.manager'

    oro_workflow.helper.transition_cron_trigger:
        class: 'Oro\Bundle\WorkflowBundle\Helper\TransitionCronTriggerHelper'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.helper.workflow_aware_entity_fetcher'

    oro_workflow.transition_trigger.cron_scheduler:
        class: 'Oro\Bundle\WorkflowBundle\Cron\TransitionTriggerCronScheduler'
        arguments:
            - '@oro_cron.deferred_scheduler'

    oro_workflow.validator_expression.dql_expression_verifier:
        class: 'Oro\Bundle\WorkflowBundle\Validator\Expression\DQLExpressionVerifier'

    oro_workflow.validator_expression.cron_expression_verifier:
        class: 'Oro\Bundle\WorkflowBundle\Validator\Expression\CronExpressionVerifier'

    oro_workflow.transition_trigger.update_decider:
        class: 'Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\TransitionTriggersUpdateDecider'
        public: false

    oro_workflow.transition_trigger_updater:
        class: 'Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\TransitionTriggersUpdater'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.transition_trigger.update_decider'
            - '@oro_workflow.transition_trigger.cron_scheduler'
            - '@oro_workflow.cache.transition_trigger_event'

    oro_workflow.transition_trigger.trigger_cron_verifier:
        class: 'Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\TransitionTriggerCronVerifier'
        public: false
        arguments:
            - '@oro_workflow.workflow_assembler'
            - '@doctrine'
        calls:
            - ['addOptionVerifier', ['cron', '@oro_workflow.validator_expression.cron_expression_verifier']]
            - ['addOptionVerifier', ['filter', '@oro_workflow.validator_expression.dql_expression_verifier']]

    oro_workflow.transition_trigger.verifier.event_trigger_relation:
        class: 'Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\Verifier\TransitionEventTriggerRelationVerifier'
        public: false

    oro_workflow.transition_trigger.verifier.event_trigger_expression:
        class: 'Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\Verifier\TransitionEventTriggerExpressionVerifier'
        public: false

    oro_workflow.transition_trigger.trigger_event_verifier:
        class: 'Oro\Bundle\WorkflowBundle\Model\TransitionTrigger\Verifier\TransitionEventTriggerCompoundVerifier'
        public: false
        calls:
            - [addVerifier, ['@oro_workflow.transition_trigger.verifier.event_trigger_relation']]
            - [addVerifier, ['@oro_workflow.transition_trigger.verifier.event_trigger_expression']]

    oro_workflow.generator.translation_key:
        class: 'Oro\Bundle\TranslationBundle\Translation\TranslationKeyGenerator'
        public: false

    oro_workflow.translation.fields_iterator:
        class: 'Oro\Bundle\WorkflowBundle\Translation\WorkflowTranslationFieldsIterator'
        arguments:
            - '@oro_workflow.generator.translation_key'

    oro_workflow.helper.translation:
        class: 'Oro\Bundle\WorkflowBundle\Helper\WorkflowTranslationHelper'
        arguments:
            - '@translator.default'
            - '@oro_translation.manager.translation'
            - '@oro_translation.helper.translation'

    oro_workflow.translation.processor:
        class: 'Oro\Bundle\WorkflowBundle\Translation\TranslationProcessor'
        arguments:
            - '@oro_workflow.translation.fields_iterator'
            - '@oro_workflow.helper.translation'
        public: false
        tags:
            - { name: oro.workflow.configuration.handler, priority: 150 }
            - { name: oro.workflow.definition_builder.extension }
            - { name: oro_workflow.changes.subscriber }

    oro_workflow.translation.translations_datagrid_links_provider:
        class: 'Oro\Bundle\WorkflowBundle\Translation\TranslationsDatagridLinksProvider'
        arguments:
            - '@oro_translation.helper.translation_route'
            - '@oro_translation.provider.language'

    oro_workflow.extension.translation_context_resolver:
        class: 'Oro\Bundle\WorkflowBundle\Extension\TranslationContextResolver'
        arguments:
            - '@translator'
            - '@oro_workflow.translation.key_template_parameters_resolver'
        tags:
            - { name: oro_translation.extension.translation_context_resolver }

    oro_workflow.translation.key_template_parameters_resolver:
        class: 'Oro\Bundle\WorkflowBundle\Translation\KeyTemplateParametersResolver'
        arguments:
            - '@translator'

    oro_workflow.filter.workflow:
        class: 'Oro\Bundle\WorkflowBundle\Filter\WorkflowFilter'
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@oro_translation.generator.translation_key'
            - '@oro_workflow.helper.translation'
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: workflow, datasource: orm }

    oro_workflow.async.execute_process_job:
        class: 'Oro\Bundle\WorkflowBundle\Async\ExecuteProcessJobProcessor'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.process.process_handler'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
