services:
    oro_workflow.twig.extension.workflow:
        class: 'Oro\Bundle\WorkflowBundle\Twig\WorkflowExtension'
        arguments:
            - '@oro_workflow.manager'
            - '@oro_workflow.translation_route.helper'
        tags:
            - { name: twig.extension }
