parameters:
    oro_workflow.twig.extension.class_name.class: Oro\Bundle\WorkflowBundle\Twig\ClassNameExtension
    oro_workflow.twig.extension.workflow.class: Oro\Bundle\WorkflowBundle\Twig\WorkflowExtension

services:
    oro_workflow.twig.extension.class_name:
        class: %oro_workflow.twig.extension.class_name.class%
        arguments:
            - @oro_workflow.doctrine_helper
        tags:
            - { name: twig.extension }

    oro_workflow.twig.extension.workflow:
        class: %oro_workflow.twig.extension.workflow.class%
        arguments:
            - @oro_workflow.registry
        tags:
            - { name: twig.extension }
