oro_workflow_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/WorkflowController.php"
    type:     rest

oro_workflow_definition_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/WorkflowDefinitionController.php"
    type:     rest

oro_workflow_entity_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/EntityController.php"
    type:     rest
