oro_workflow_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/WorkflowController.php"
    type:     rest
    prefix:   /workflow

oro_workflow_definition_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/WorkflowDefinitionController.php"
    type:     rest
    prefix:   /workflow-definition
